[build]
  publish = "."
  command = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions.site-router]
  included_files = ["templates/**"]

[functions.resolve-subdomain]
  included_files = ["templates/**"]

[[redirects]]
  from = "/s/*"
  to = "/.netlify/functions/site-router"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
