export function getSiteSchemaStatements() {
  const tables = [
    `CREATE TABLE IF NOT EXISTS categories (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      name TEXT NOT NULL,
      slug TEXT NOT NULL,
      parent_id TEXT,
      description TEXT,
      subtitle TEXT,
      show_on_home INTEGER DEFAULT 1,
      image_url TEXT,
      display_order INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      seo_title TEXT,
      seo_description TEXT,
      seo_og_image TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, slug)
    )`,

    `CREATE TABLE IF NOT EXISTS products (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      category_id TEXT,
      subcategory_id TEXT,
      name TEXT NOT NULL,
      slug TEXT NOT NULL,
      description TEXT,
      short_description TEXT,
      price REAL NOT NULL,
      compare_price REAL,
      cost_price REAL,
      sku TEXT,
      barcode TEXT,
      stock INTEGER DEFAULT 0,
      low_stock_threshold INTEGER DEFAULT 3,
      weight REAL,
      dimensions TEXT,
      images TEXT,
      thumbnail_url TEXT,
      tags TEXT,
      options TEXT,
      is_featured INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      seo_title TEXT,
      seo_description TEXT,
      seo_og_image TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, slug)
    )`,

    `CREATE TABLE IF NOT EXISTS product_variants (
      id TEXT PRIMARY KEY,
      product_id TEXT NOT NULL,
      name TEXT NOT NULL,
      sku TEXT,
      price REAL NOT NULL,
      compare_price REAL,
      stock INTEGER DEFAULT 0,
      attributes TEXT,
      image_url TEXT,
      is_active INTEGER DEFAULT 1,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS orders (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      user_id TEXT,
      order_number TEXT UNIQUE NOT NULL,
      status TEXT DEFAULT 'pending',
      items TEXT NOT NULL,
      subtotal REAL NOT NULL,
      discount REAL DEFAULT 0,
      shipping_cost REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL NOT NULL,
      currency TEXT DEFAULT 'INR',
      payment_method TEXT,
      payment_status TEXT DEFAULT 'pending',
      payment_id TEXT,
      razorpay_order_id TEXT,
      razorpay_payment_id TEXT,
      razorpay_signature TEXT,
      shipping_address TEXT NOT NULL,
      billing_address TEXT,
      customer_name TEXT NOT NULL,
      customer_email TEXT,
      customer_phone TEXT NOT NULL,
      coupon_code TEXT,
      notes TEXT,
      tracking_number TEXT,
      carrier TEXT,
      shipped_at TEXT,
      delivered_at TEXT,
      cancelled_at TEXT,
      cancellation_reason TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS guest_orders (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      order_number TEXT UNIQUE NOT NULL,
      status TEXT DEFAULT 'pending',
      items TEXT NOT NULL,
      subtotal REAL NOT NULL,
      discount REAL DEFAULT 0,
      shipping_cost REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL NOT NULL,
      currency TEXT DEFAULT 'INR',
      payment_method TEXT,
      payment_status TEXT DEFAULT 'pending',
      razorpay_order_id TEXT,
      razorpay_payment_id TEXT,
      shipping_address TEXT NOT NULL,
      customer_name TEXT NOT NULL,
      customer_email TEXT,
      customer_phone TEXT NOT NULL,
      tracking_number TEXT,
      carrier TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS carts (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      user_id TEXT,
      session_id TEXT,
      items TEXT NOT NULL DEFAULT '[]',
      subtotal REAL DEFAULT 0,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS wishlists (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      product_id TEXT NOT NULL,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, user_id, product_id)
    )`,

    `CREATE TABLE IF NOT EXISTS site_customers (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      email TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      phone TEXT,
      email_verified INTEGER DEFAULT 0,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, email)
    )`,

    `CREATE TABLE IF NOT EXISTS site_customer_sessions (
      id TEXT PRIMARY KEY,
      customer_id TEXT NOT NULL,
      site_id TEXT NOT NULL,
      token TEXT NOT NULL,
      expires_at TEXT NOT NULL,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS customer_addresses (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      label TEXT DEFAULT 'Home',
      first_name TEXT NOT NULL,
      last_name TEXT,
      phone TEXT,
      house_number TEXT NOT NULL,
      road_name TEXT,
      city TEXT NOT NULL,
      state TEXT NOT NULL,
      pin_code TEXT NOT NULL,
      is_default INTEGER DEFAULT 0,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS customer_password_resets (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      token TEXT NOT NULL UNIQUE,
      expires_at TEXT NOT NULL,
      used INTEGER DEFAULT 0,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS customer_email_verifications (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      token TEXT NOT NULL UNIQUE,
      expires_at TEXT NOT NULL,
      used INTEGER DEFAULT 0,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS coupons (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      code TEXT NOT NULL,
      type TEXT NOT NULL,
      value REAL NOT NULL,
      min_order_value REAL DEFAULT 0,
      max_discount REAL,
      usage_limit INTEGER,
      used_count INTEGER DEFAULT 0,
      starts_at TEXT,
      expires_at TEXT,
      is_active INTEGER DEFAULT 1,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, code)
    )`,

    `CREATE TABLE IF NOT EXISTS notifications (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      user_id TEXT,
      push_token TEXT NOT NULL,
      endpoint TEXT,
      p256dh TEXT,
      auth TEXT,
      is_active INTEGER DEFAULT 1,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS reviews (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      product_id TEXT NOT NULL,
      order_id TEXT,
      user_id TEXT,
      customer_name TEXT NOT NULL,
      rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5),
      title TEXT,
      content TEXT,
      images TEXT,
      status TEXT DEFAULT 'pending',
      is_verified INTEGER DEFAULT 0,
      is_approved INTEGER DEFAULT 0,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS page_seo (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      page_type TEXT NOT NULL,
      seo_title TEXT,
      seo_description TEXT,
      seo_og_image TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, page_type)
    )`,

    `CREATE TABLE IF NOT EXISTS site_media (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      site_id TEXT NOT NULL,
      storage_key TEXT NOT NULL UNIQUE,
      size_bytes INTEGER NOT NULL,
      media_type TEXT DEFAULT 'image',
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS site_usage (
      site_id TEXT PRIMARY KEY,
      d1_bytes_used INTEGER DEFAULT 0,
      r2_bytes_used INTEGER DEFAULT 0,
      baseline_bytes INTEGER DEFAULT 0,
      baseline_updated_at TEXT,
      last_updated TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS activity_log (
      id TEXT PRIMARY KEY,
      site_id TEXT,
      user_id TEXT,
      action TEXT NOT NULL,
      entity_type TEXT,
      entity_id TEXT,
      details TEXT,
      ip_address TEXT,
      user_agent TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS addresses (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      phone TEXT NOT NULL,
      line1 TEXT NOT NULL,
      line2 TEXT,
      city TEXT NOT NULL,
      state TEXT NOT NULL,
      pincode TEXT NOT NULL,
      country TEXT DEFAULT 'India',
      is_default INTEGER DEFAULT 0,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS page_views (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      site_id TEXT NOT NULL,
      page_path TEXT NOT NULL,
      referrer TEXT,
      country TEXT,
      device_type TEXT,
      browser TEXT,
      visitor_id TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS cancellation_requests (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      order_id TEXT NOT NULL,
      order_number TEXT,
      order_type TEXT DEFAULT 'order',
      reason TEXT NOT NULL,
      reason_detail TEXT,
      status TEXT DEFAULT 'requested',
      admin_note TEXT,
      customer_name TEXT,
      customer_email TEXT,
      customer_phone TEXT,
      cancel_token TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS return_requests (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      order_id TEXT NOT NULL,
      order_number TEXT,
      items TEXT,
      reason TEXT NOT NULL,
      reason_detail TEXT,
      photos TEXT,
      resolution TEXT,
      status TEXT DEFAULT 'requested',
      admin_note TEXT,
      refund_amount REAL,
      refund_id TEXT,
      return_token TEXT,
      customer_name TEXT,
      customer_email TEXT,
      customer_phone TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS site_staff (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      email TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      permissions TEXT DEFAULT '[]',
      is_active INTEGER DEFAULT 1,
      failed_login_attempts INTEGER DEFAULT 0,
      locked_until TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, email)
    )`,

    `CREATE TABLE IF NOT EXISTS site_config (
      site_id TEXT PRIMARY KEY,
      brand_name TEXT,
      category TEXT,
      logo_url TEXT,
      favicon_url TEXT,
      primary_color TEXT DEFAULT '#000000',
      secondary_color TEXT DEFAULT '#ffffff',
      phone TEXT,
      email TEXT,
      address TEXT,
      social_links TEXT,
      settings TEXT DEFAULT '{}',
      currency TEXT DEFAULT 'INR',
      seo_title TEXT,
      seo_description TEXT,
      seo_og_image TEXT,
      seo_robots TEXT DEFAULT 'index, follow',
      google_verification TEXT,
      og_title TEXT,
      og_description TEXT,
      og_image TEXT,
      og_type TEXT DEFAULT 'website',
      twitter_card TEXT DEFAULT 'summary_large_image',
      twitter_title TEXT,
      twitter_description TEXT,
      twitter_image TEXT,
      twitter_site TEXT,
      theme_config TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    // System B (per-site shopper translation) cache. Each row is a single
    // unique (site, source_text_hash, source_lang, target_lang) tuple — the
    // SHA-256 hash lets us look up by content without storing the source
    // string twice. char_count records the source-text character cost for
    // observability/audit. Cache hits skip Microsoft entirely so the same
    // text never bills the merchant twice.
    `CREATE TABLE IF NOT EXISTS translation_cache (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      text_hash TEXT NOT NULL,
      source_lang TEXT NOT NULL DEFAULT 'auto',
      target_lang TEXT NOT NULL,
      translated_text TEXT NOT NULL,
      char_count INTEGER NOT NULL DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, text_hash, source_lang, target_lang)
    )`,

    `CREATE TABLE IF NOT EXISTS blog_posts (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      title TEXT NOT NULL,
      slug TEXT NOT NULL,
      content TEXT NOT NULL DEFAULT '',
      excerpt TEXT DEFAULT '',
      cover_image TEXT DEFAULT '',
      status TEXT DEFAULT 'draft',
      author TEXT DEFAULT '',
      tags TEXT DEFAULT '[]',
      meta_title TEXT DEFAULT '',
      meta_description TEXT DEFAULT '',
      published_at TEXT,
      row_size_bytes INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, slug)
    )`,
  ];

  const indexes = [
    'CREATE INDEX IF NOT EXISTS idx_categories_site ON categories(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories(site_id, slug)',
    'CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories(parent_id)',
    'CREATE INDEX IF NOT EXISTS idx_products_site ON products(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id)',
    'CREATE INDEX IF NOT EXISTS idx_products_site_slug ON products(site_id, slug)',
    'CREATE INDEX IF NOT EXISTS idx_products_featured ON products(site_id, is_featured)',
    'CREATE INDEX IF NOT EXISTS idx_variants_product ON product_variants(product_id)',
    'CREATE INDEX IF NOT EXISTS idx_orders_site ON orders(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(order_number)',
    'CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(site_id, status)',
    'CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(site_id, created_at)',
    'CREATE INDEX IF NOT EXISTS idx_guest_orders_site ON guest_orders(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_guest_orders_number ON guest_orders(order_number)',
    'CREATE INDEX IF NOT EXISTS idx_carts_user ON carts(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_carts_session ON carts(session_id)',
    'CREATE INDEX IF NOT EXISTS idx_carts_site ON carts(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_wishlists_user ON wishlists(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_wishlists_site ON wishlists(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_site_customers_site ON site_customers(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_site_customers_email ON site_customers(site_id, email)',
    'CREATE INDEX IF NOT EXISTS idx_customer_sessions_token ON site_customer_sessions(token)',
    'CREATE INDEX IF NOT EXISTS idx_customer_sessions_customer ON site_customer_sessions(customer_id)',
    'CREATE INDEX IF NOT EXISTS idx_customer_addresses_customer ON customer_addresses(customer_id)',
    'CREATE INDEX IF NOT EXISTS idx_customer_addresses_site ON customer_addresses(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_customer_pw_reset_token ON customer_password_resets(token)',
    'CREATE INDEX IF NOT EXISTS idx_customer_email_verify_token ON customer_email_verifications(token)',
    'CREATE INDEX IF NOT EXISTS idx_coupons_site ON coupons(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_coupons_code ON coupons(site_id, code)',
    'CREATE INDEX IF NOT EXISTS idx_notifications_site ON notifications(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_reviews_product ON reviews(product_id)',
    'CREATE INDEX IF NOT EXISTS idx_reviews_site ON reviews(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_activity_site ON activity_log(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_activity_user ON activity_log(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log(created_at)',
    'CREATE INDEX IF NOT EXISTS idx_site_media_site ON site_media(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_site_media_key ON site_media(storage_key)',
    'CREATE INDEX IF NOT EXISTS idx_addresses_user ON addresses(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_site_staff_site ON site_staff(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_site_staff_email ON site_staff(site_id, email)',
    'CREATE INDEX IF NOT EXISTS idx_translation_cache_lookup ON translation_cache(site_id, text_hash, source_lang, target_lang)',
    'CREATE INDEX IF NOT EXISTS idx_translation_cache_site ON translation_cache(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_cancel_requests_site ON cancellation_requests(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_cancel_requests_order ON cancellation_requests(order_id)',
    'CREATE INDEX IF NOT EXISTS idx_return_requests_site ON return_requests(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_return_requests_order ON return_requests(order_id)',
    'CREATE INDEX IF NOT EXISTS idx_return_requests_token ON return_requests(return_token)',
    'CREATE INDEX IF NOT EXISTS idx_page_views_site ON page_views(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_page_views_created ON page_views(site_id, created_at)',
    'CREATE INDEX IF NOT EXISTS idx_page_views_visitor ON page_views(site_id, visitor_id)',
    'CREATE INDEX IF NOT EXISTS idx_page_views_path ON page_views(site_id, page_path)',
    'CREATE INDEX IF NOT EXISTS idx_blog_posts_site ON blog_posts(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(site_id, slug)',
    'CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON blog_posts(site_id, status)',
    'CREATE INDEX IF NOT EXISTS idx_blog_posts_published ON blog_posts(site_id, published_at)',
  ];

  const addColumnMigrations = [
    'ALTER TABLE categories ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE products ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE product_variants ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE orders ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE guest_orders ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE carts ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE wishlists ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE site_customers ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE site_customer_sessions ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE customer_addresses ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE customer_password_resets ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE customer_email_verifications ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE coupons ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE notifications ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE notifications ADD COLUMN language TEXT',
    'ALTER TABLE reviews ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE page_seo ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE site_media ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE activity_log ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE addresses ADD COLUMN row_size_bytes INTEGER DEFAULT 0',
    'ALTER TABLE site_usage ADD COLUMN baseline_bytes INTEGER DEFAULT 0',
    'ALTER TABLE site_usage ADD COLUMN baseline_updated_at TEXT',
    'ALTER TABLE products ADD COLUMN options TEXT',
    'ALTER TABLE orders ADD COLUMN confirmed_at TEXT',
    'ALTER TABLE orders ADD COLUMN packed_at TEXT',
    'ALTER TABLE orders ADD COLUMN cancel_token TEXT',
    'ALTER TABLE orders ADD COLUMN return_token TEXT',
    'ALTER TABLE guest_orders ADD COLUMN cancel_token TEXT',
    'ALTER TABLE guest_orders ADD COLUMN return_token TEXT',
    'ALTER TABLE guest_orders ADD COLUMN cancellation_reason TEXT',
    'ALTER TABLE orders ADD COLUMN shipping_cost REAL DEFAULT 0',
    'ALTER TABLE orders ADD COLUMN tax REAL DEFAULT 0',
    'ALTER TABLE guest_orders ADD COLUMN shipping_cost REAL DEFAULT 0',
    'ALTER TABLE products ADD COLUMN hsn_code TEXT',
    'ALTER TABLE products ADD COLUMN gst_rate REAL DEFAULT 0',
    'ALTER TABLE orders ADD COLUMN invoice_token TEXT',
    'ALTER TABLE orders ADD COLUMN customer_gstin TEXT',
    'ALTER TABLE guest_orders ADD COLUMN invoice_token TEXT',
    'ALTER TABLE guest_orders ADD COLUMN customer_gstin TEXT',
    'ALTER TABLE site_config ADD COLUMN seo_keywords TEXT',
    'ALTER TABLE products ADD COLUMN seo_keywords TEXT',
    'ALTER TABLE categories ADD COLUMN seo_keywords TEXT',
    'ALTER TABLE page_seo ADD COLUMN seo_keywords TEXT',
    'ALTER TABLE blog_posts ADD COLUMN featured_image TEXT',
    'ALTER TABLE blog_posts ADD COLUMN author_name TEXT',
    'ALTER TABLE blog_posts ADD COLUMN seo_title TEXT',
    'ALTER TABLE blog_posts ADD COLUMN seo_description TEXT',
    'ALTER TABLE blog_posts ADD COLUMN seo_og_image TEXT',
    'ALTER TABLE blog_posts ADD COLUMN seo_keywords TEXT',
    'ALTER TABLE site_customers ADD COLUMN whatsapp_opted_in INTEGER DEFAULT 0',
    'ALTER TABLE orders ADD COLUMN whatsapp_opted_in INTEGER DEFAULT 0',
    'ALTER TABLE guest_orders ADD COLUMN whatsapp_opted_in INTEGER DEFAULT 0',
    'ALTER TABLE carts ADD COLUMN reminder_sent_at TEXT',
    'ALTER TABLE carts ADD COLUMN reminder_count INTEGER DEFAULT 0',
    'ALTER TABLE orders ADD COLUMN placed_in_language TEXT',
    'ALTER TABLE guest_orders ADD COLUMN placed_in_language TEXT',
    'ALTER TABLE site_customers ADD COLUMN preferred_lang TEXT',
    'ALTER TABLE carts ADD COLUMN language TEXT',
    // Shiprocket integration columns
    'ALTER TABLE orders ADD COLUMN shiprocket_order_id TEXT',
    'ALTER TABLE orders ADD COLUMN shiprocket_shipment_id TEXT',
    'ALTER TABLE orders ADD COLUMN shiprocket_awb TEXT',
    'ALTER TABLE orders ADD COLUMN shiprocket_courier TEXT',
    'ALTER TABLE orders ADD COLUMN shiprocket_label_url TEXT',
    'ALTER TABLE orders ADD COLUMN shiprocket_status TEXT',
    'ALTER TABLE orders ADD COLUMN shiprocket_last_event_at TEXT',
    'ALTER TABLE orders ADD COLUMN shiprocket_error TEXT',
    'ALTER TABLE orders ADD COLUMN shiprocket_claimed_at TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_order_id TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_shipment_id TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_awb TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_courier TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_label_url TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_status TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_last_event_at TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_error TEXT',
    'ALTER TABLE guest_orders ADD COLUMN shiprocket_claimed_at TEXT',
    // T13: Razorpay refund tracking. We persist the Razorpay refund_id +
    // timestamp on the order itself so the admin UI can show "Refunded" and
    // the refund endpoint can be idempotent (skip when refund_id already set).
    'ALTER TABLE orders ADD COLUMN refund_id TEXT',
    'ALTER TABLE orders ADD COLUMN refund_amount REAL',
    'ALTER TABLE orders ADD COLUMN refunded_at TEXT',
    'ALTER TABLE guest_orders ADD COLUMN refund_id TEXT',
    'ALTER TABLE guest_orders ADD COLUMN refund_amount REAL',
    'ALTER TABLE guest_orders ADD COLUMN refunded_at TEXT',
    // Per-section color schemes (Brand/Inverse/Accent + custom). Stored as
    // JSON: { schemes: [...], sectionAssignments: { sectionId: schemeId } }.
    'ALTER TABLE site_config ADD COLUMN theme_config TEXT',
  ];

  return [...tables, ...indexes, ...addColumnMigrations];
}
