export function getSiteSchemaStatements() {
  const tables = [
    `CREATE TABLE IF NOT EXISTS categories (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      name TEXT NOT NULL,
      slug TEXT NOT NULL,
      parent_id TEXT,
      description TEXT,
      subtitle TEXT,
      show_on_home INTEGER DEFAULT 1,
      image_url TEXT,
      display_order INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      seo_title TEXT,
      seo_description TEXT,
      seo_og_image TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, slug)
    )`,

    `CREATE TABLE IF NOT EXISTS products (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      category_id TEXT,
      name TEXT NOT NULL,
      slug TEXT NOT NULL,
      description TEXT,
      short_description TEXT,
      price REAL NOT NULL,
      compare_price REAL,
      cost_price REAL,
      sku TEXT,
      barcode TEXT,
      stock INTEGER DEFAULT 0,
      low_stock_threshold INTEGER DEFAULT 5,
      weight REAL,
      dimensions TEXT,
      images TEXT,
      thumbnail_url TEXT,
      tags TEXT,
      is_featured INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      seo_title TEXT,
      seo_description TEXT,
      seo_og_image TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, slug)
    )`,

    `CREATE TABLE IF NOT EXISTS product_variants (
      id TEXT PRIMARY KEY,
      product_id TEXT NOT NULL,
      name TEXT NOT NULL,
      sku TEXT,
      price REAL NOT NULL,
      compare_price REAL,
      stock INTEGER DEFAULT 0,
      attributes TEXT,
      image_url TEXT,
      is_active INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS orders (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      user_id TEXT,
      order_number TEXT UNIQUE NOT NULL,
      status TEXT DEFAULT 'pending',
      items TEXT NOT NULL,
      subtotal REAL NOT NULL,
      discount REAL DEFAULT 0,
      shipping_cost REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL NOT NULL,
      currency TEXT DEFAULT 'INR',
      payment_method TEXT,
      payment_status TEXT DEFAULT 'pending',
      payment_id TEXT,
      razorpay_order_id TEXT,
      razorpay_payment_id TEXT,
      razorpay_signature TEXT,
      shipping_address TEXT NOT NULL,
      billing_address TEXT,
      customer_name TEXT NOT NULL,
      customer_email TEXT,
      customer_phone TEXT NOT NULL,
      coupon_code TEXT,
      notes TEXT,
      tracking_number TEXT,
      carrier TEXT,
      shipped_at TEXT,
      delivered_at TEXT,
      cancelled_at TEXT,
      cancellation_reason TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS guest_orders (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      order_number TEXT UNIQUE NOT NULL,
      status TEXT DEFAULT 'pending',
      items TEXT NOT NULL,
      subtotal REAL NOT NULL,
      discount REAL DEFAULT 0,
      shipping_cost REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL NOT NULL,
      currency TEXT DEFAULT 'INR',
      payment_method TEXT,
      payment_status TEXT DEFAULT 'pending',
      razorpay_order_id TEXT,
      razorpay_payment_id TEXT,
      shipping_address TEXT NOT NULL,
      customer_name TEXT NOT NULL,
      customer_email TEXT,
      customer_phone TEXT NOT NULL,
      tracking_number TEXT,
      carrier TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS carts (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      user_id TEXT,
      session_id TEXT,
      items TEXT NOT NULL DEFAULT '[]',
      subtotal REAL DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS wishlists (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      product_id TEXT NOT NULL,
      created_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, user_id, product_id)
    )`,

    `CREATE TABLE IF NOT EXISTS site_customers (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      email TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      phone TEXT,
      email_verified INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, email)
    )`,

    `CREATE TABLE IF NOT EXISTS site_customer_sessions (
      id TEXT PRIMARY KEY,
      customer_id TEXT NOT NULL,
      site_id TEXT NOT NULL,
      token TEXT NOT NULL,
      expires_at TEXT NOT NULL,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS customer_addresses (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      label TEXT DEFAULT 'Home',
      first_name TEXT NOT NULL,
      last_name TEXT,
      phone TEXT,
      house_number TEXT NOT NULL,
      road_name TEXT,
      city TEXT NOT NULL,
      state TEXT NOT NULL,
      pin_code TEXT NOT NULL,
      is_default INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS customer_password_resets (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      token TEXT NOT NULL UNIQUE,
      expires_at TEXT NOT NULL,
      used INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS customer_email_verifications (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      customer_id TEXT NOT NULL,
      token TEXT NOT NULL UNIQUE,
      expires_at TEXT NOT NULL,
      used INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS coupons (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      code TEXT NOT NULL,
      type TEXT NOT NULL,
      value REAL NOT NULL,
      min_order_value REAL DEFAULT 0,
      max_discount REAL,
      usage_limit INTEGER,
      used_count INTEGER DEFAULT 0,
      starts_at TEXT,
      expires_at TEXT,
      is_active INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, code)
    )`,

    `CREATE TABLE IF NOT EXISTS notifications (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      user_id TEXT,
      push_token TEXT NOT NULL,
      endpoint TEXT,
      p256dh TEXT,
      auth TEXT,
      is_active INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS reviews (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      product_id TEXT NOT NULL,
      user_id TEXT,
      customer_name TEXT NOT NULL,
      rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5),
      title TEXT,
      content TEXT,
      images TEXT,
      is_verified INTEGER DEFAULT 0,
      is_approved INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS page_seo (
      id TEXT PRIMARY KEY,
      site_id TEXT NOT NULL,
      page_type TEXT NOT NULL,
      seo_title TEXT,
      seo_description TEXT,
      seo_og_image TEXT,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now')),
      UNIQUE(site_id, page_type)
    )`,

    `CREATE TABLE IF NOT EXISTS site_media (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      site_id TEXT NOT NULL,
      storage_key TEXT NOT NULL UNIQUE,
      size_bytes INTEGER NOT NULL,
      media_type TEXT DEFAULT 'image',
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS site_usage (
      site_id TEXT PRIMARY KEY,
      d1_bytes_used INTEGER DEFAULT 0,
      r2_bytes_used INTEGER DEFAULT 0,
      last_updated TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS activity_log (
      id TEXT PRIMARY KEY,
      site_id TEXT,
      user_id TEXT,
      action TEXT NOT NULL,
      entity_type TEXT,
      entity_id TEXT,
      details TEXT,
      ip_address TEXT,
      user_agent TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    )`,

    `CREATE TABLE IF NOT EXISTS addresses (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      phone TEXT NOT NULL,
      line1 TEXT NOT NULL,
      line2 TEXT,
      city TEXT NOT NULL,
      state TEXT NOT NULL,
      pincode TEXT NOT NULL,
      country TEXT DEFAULT 'India',
      is_default INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now')),
      updated_at TEXT DEFAULT (datetime('now'))
    )`,
  ];

  const indexes = [
    'CREATE INDEX IF NOT EXISTS idx_categories_site ON categories(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories(site_id, slug)',
    'CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories(parent_id)',
    'CREATE INDEX IF NOT EXISTS idx_products_site ON products(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id)',
    'CREATE INDEX IF NOT EXISTS idx_products_site_slug ON products(site_id, slug)',
    'CREATE INDEX IF NOT EXISTS idx_products_featured ON products(site_id, is_featured)',
    'CREATE INDEX IF NOT EXISTS idx_variants_product ON product_variants(product_id)',
    'CREATE INDEX IF NOT EXISTS idx_orders_site ON orders(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(order_number)',
    'CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(site_id, status)',
    'CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(site_id, created_at)',
    'CREATE INDEX IF NOT EXISTS idx_guest_orders_site ON guest_orders(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_guest_orders_number ON guest_orders(order_number)',
    'CREATE INDEX IF NOT EXISTS idx_carts_user ON carts(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_carts_session ON carts(session_id)',
    'CREATE INDEX IF NOT EXISTS idx_carts_site ON carts(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_wishlists_user ON wishlists(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_wishlists_site ON wishlists(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_site_customers_site ON site_customers(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_site_customers_email ON site_customers(site_id, email)',
    'CREATE INDEX IF NOT EXISTS idx_customer_sessions_token ON site_customer_sessions(token)',
    'CREATE INDEX IF NOT EXISTS idx_customer_sessions_customer ON site_customer_sessions(customer_id)',
    'CREATE INDEX IF NOT EXISTS idx_customer_addresses_customer ON customer_addresses(customer_id)',
    'CREATE INDEX IF NOT EXISTS idx_customer_addresses_site ON customer_addresses(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_customer_pw_reset_token ON customer_password_resets(token)',
    'CREATE INDEX IF NOT EXISTS idx_customer_email_verify_token ON customer_email_verifications(token)',
    'CREATE INDEX IF NOT EXISTS idx_coupons_site ON coupons(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_coupons_code ON coupons(site_id, code)',
    'CREATE INDEX IF NOT EXISTS idx_notifications_site ON notifications(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_reviews_product ON reviews(product_id)',
    'CREATE INDEX IF NOT EXISTS idx_reviews_site ON reviews(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_activity_site ON activity_log(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_activity_user ON activity_log(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log(created_at)',
    'CREATE INDEX IF NOT EXISTS idx_site_media_site ON site_media(site_id)',
    'CREATE INDEX IF NOT EXISTS idx_site_media_key ON site_media(storage_key)',
    'CREATE INDEX IF NOT EXISTS idx_addresses_user ON addresses(user_id)',
  ];

  return [...tables, ...indexes];
}
